# Jekyll
markdown: rdiscount
highlighter: "rouge"
permalink: /:title.html

# Conference info
conf:
  name: "GCP Next Extended '17'"
  description: "Google Cloud Platform NEXT Extended 2017"
  date: "29 de abril de 2017"
  price: "Gratuito!"
  address: "Av. Murilo Dantas, 300 - Farolândia, Aracaju - SE, 49032-490"
  venue: "UNIT Farolândia"
  city: "Aracaju, Sergipe"

# Site info
site:
  author: "GDG Aracaju"
  url: "http://gcp.gdgaracaju.com.br"
  favicon: "http://www.gdgaracaju.com.br/favicon.ico"
  googleanalytics: "UA-49492619-1"
  images:
    cover: "./img/og_image.png"
    facebook: "http://gcp.gdgaracaju.com.br/img/og_image.png"

subscribe_text: ""
subscribe_url: ""

# Active sections on the website
sections:
  about: true
  c4p: false
  location: true
  speakers: false
  schedule: true
  sponsors: false
  partners: true
  contact: false
  tickets: false

# Organizers list
organizers:
  -
    name: "GDG Aracaju"
    photo: "./img/partners/gdgaracaju.png"
    url: "http://site.gdgaracaju.com.br/"
    bio: ""
    company: ""
  -
    name: "Erick Mendonça"
    photo: "./img/speakers/erick_mendonca.jpg"
    url: "http://github.com/erickmendonca"
    bio: ""
    company: "UFS"
  -
    name: "Jéssica Costa"
    photo: "./img/speakers/jessica_costa.jpg"
    url: "http://github.com/erickmendonca"
    bio: ""
    company: ""
  -
    name: "Raphael Pantaleão"
    photo: "./img/speakers/raphael.jpg"
    url: "http://github.com/raphaelpanta"
    bio: ""
    company: ""
  -
    name: "Roberto Brandini"
    photo: "./img/speakers/roberto_brandini.jpg"
    url: "https://www.facebook.com/roberto.brandini"
    bio: ""
    company: ""
  -
    name: "Ítalo Marcel"
    photo: "./img/speakers/italo_marcel.jpg"
    url: "https://www.facebook.com/italo.marcel"
    bio: ""
    company: ""

# Speakers list
speakers:
  -
    name: "Dennison Souza"
    url: ""
    photo: "./img/speakers/dennison_souza.jpg"
    title: "Docker container engine"
    details: ""

# Schedule
schedule:
  -
    day: "3004"
    name: "30/04 GCP Next Extended"
    description: ""
    url: ""
    agenda:
      -
        name: "Keynote: What's next for Cloud"
        time:
          start: "14:00"
          end: "16:00"
        description: ""
        speaker:
          name: ""
          photo: ""
          url: ""
      -
        name: "Intervalo e coffee-break"
        time:
          start: "16:00"
          end: "16:30"
        description: ""
        speaker:
          name: ""
          photo: ""
          url: ""
      -
        name: "Palestra: Docker Container Engine"
        time:
          start: "16:30"
          end: "17:30"
        description: "Docker permite você empacotar uma aplicação com todas as suas dependências em uma unidade de desenvolmento software padronizado. Dennisson Souza mostrará como Containers Docker engloba tudo que é preciso para rodar um software e garantir que o software rodará corretamente mesmo em diferentes ambientes."
        speaker:
          name: "Dennison Souza"
          photo: "./img/speakers/dennison_souza.jpg"
          url: ""
      -
        name: "Palestra: Virtualização"
        time:
          start: "17:30"
          end: "18:30"
        description: "Virtualização é importante para qualquer setor de TI. O poder que as máquinas virtuais trazem é muito benéfico para as empresas, como facilidades de escalabilidade, configuração, gerenciamento, entre outros. Roberto Brandini nos mostrará como ele usa virtualização no dia a dia de sua empresa, a DP Sistemas."
        speaker:
          name: "Roberto Brandini"
          photo: "./img/speakers/roberto_brandini.jpg"
          url: ""
      -
        name: "Sorteio de Brindes e Encerramento"
        time:
          start: "18:30"
          end: "19:00"
        description: ""
        speaker:
          name: ""
          photo: ""
          url: ""


# List of Sponsors
sponsors:
  -
    name: "Google Developers"
    logo: "./img/partners/gd.jpg"
    url: "http://developers.google.com/"


# List of Partners
partners:
  -
    name: "UNIT"
    logo: "./img/partners/unit.jpg"
    url: "https://www.unit.br"

# About section
about_section:
   title: "Sobre"
   description: ""

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: "Se você tem interesse em contribuir com a comunidade nessa jornada, faça uma proposta :) Nós estamos interessados em testes, Firebase, aplicativos híbridos, criação de APIs, backend, além de conteúdo sobre desenvolvimento Android."
   c4p_url: "http://goo.gl/forms/Wbcc4OQfgB"
   c4p_caption: "Preencha o form!"
   c4p_rules_url: ""
   c4p_rules_caption: ""

# Contact section
contact_section:
   title: "Contato"
   text: "Fale conosco se tiver qualquer dúvida!"
   contacts:
   -
     title: "Email"
     link: "mailto:gdgaracaju@gmail.com"
   -
     title: "Google+"
     link: "https://plus.google.com/communities/100418157558568471841"
   email: "gdgaracaju@gmail.com"
   twitter_url: "http://twitter.com/gdgaracaju"
   twitter_username: "@gdgaracaju"
   show_form: false
   form:
    action: "contato.php"
    name: "What's your name?"
    email: "What's your email?"
    message: "Write a message"
    send_button: "Send"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: false
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"

# Schedule section
schedule_section:
   title: "Programação"
   text: "A programação pode sofrer alterações sem avisos prévios."
   time: "Hora"
   slot: "Atividade"
   description: "Descrição"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: false
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"
