# Jekyll
markdown: rdiscount
highlighter: "rouge"
permalink: /:title.html

# Conference info
conf:
  name: "GCP Next Extended"
  description: "Google Cloud Platform NEXT Extended"
  date: "30 de abril de 2016"
  price: "Gratuito!"
  address: "Travessa Sargento Duque, 85 - Bairro Industrial"
  venue: "FANESE - Faculdade de Administração e Negócios de Sergipe"
  city: "Aracaju, Sergipe"

# Site info
site:
  author: "GDG Aracaju"
  url: "http://android.gdgaracaju.com.br"
  favicon: "http://www.gdgaracaju.com.br/favicon.ico"
  googleanalytics: "UA-49492619-1"
  images:
    cover: "./img/og_image.png"
    facebook: "http://android.gdgaracaju.com.br/img/og_image.png"

subscribe_text: "Inscreva-se no Meetup!"
subscribe_url: "http://www.meetup.com/pt-BR/GDG-Aracaju/events/228405725/"

# Active sections on the website
sections:
  about: true
  c4p: false
  location: true
  speakers: false
  schedule: true
  sponsors: true
  partners: true
  contact: false
  tickets: false

# Organizers list
organizers:
  -
    name: "GDG Aracaju"
    photo: "./img/partners/gdgaracaju.png"
    url: "http://site.gdgaracaju.com.br/"
    bio: ""
    company: ""
  -
    name: "Erick Mendonça"
    photo: "./img/speakers/erick_mendonca.jpg"
    url: "http://github.com/erickmendonca"
    bio: "Formando na Universidade Federal de Sergipe e possui experiência como desenvolvedor e analista de sistemas. Co-organizador do Google Developer Group Aracaju, busca compartilhar conhecimento e aperfeiçoar a comunidade local de desenvolvedores e empreendedores através de eventos técnicos e encontros descontraídos para incentivar o crescimento e a empatia da comunidade local."
    company: "UFS"
  -
    name: "Fernando Mendonça"
    photo: "./img/speakers/fernando.jpg"
    url: "http://github.com/erickmendonca"
    bio: ""
    company: ""
  -
    name: "Raphael Pantaleão"
    photo: "./img/speakers/raphael.jpg"
    url: "http://github.com/raphaelpanta"
    bio: ""
    company: ""
  -
    name: "Roberto Brandini"
    photo: "./img/speakers/roberto_brandini.jpg"
    url: "https://www.facebook.com/roberto.brandini"
    bio: ""
    company: ""

# Speakers list
speakers:
  -
    name: "Dennison Souza"
    url: ""
    photo: "./img/speakers/dennison_souza.jpg"
    title: "Docker container engine"
    details: ""

# Schedule
schedule:
  -
    day: "3004"
    name: "30/04 GCP Next Extended"
    description: "O Google Cloud Platform NEXT foi o maior evento sobre a plataforma de computação em nuvem do Google. Houveram grandes anúncios para a plataforma, como o serviço de aprendizado de máquina e outros avanços gigantescos. Grandes empresas já usam a nuvem do Google: Spotify, Snapchat, Disney e Coca-cola são apenas alguns exemplos. Aqui no GDG Aracaju vamos nos reunir e fazer uma versão extendida do evento que rolou no último março em San Francisco, assistir a keynote, discutir as novidades e aprender mais com uma palestra local."
    url: ""
    agenda:
      -
        name: "Keynote: What's next for Cloud"
        time:
          start: "14:00"
          end: "16:00"
        description: ""
        speaker:
          name: ""
          photo: ""
          url: ""
      -
        name: "Intervalo e coffee-break"
        time:
          start: "16:00"
          end: "16:30"
        description: ""
        speaker:
          name: ""
          photo: ""
          url: ""
      -
        name: "Palestra: Docker Container Engine"
        time:
          start: "16:30"
          end: "17:30"
        description: "Docker permite você empacotar uma aplicação com todas as suas dependências em uma unidade de desenvolmento software padronizado. Dennisson Souza mostrará como Containers Docker engloba tudo que é preciso para rodar um software e garantir que o software rodará corretamente mesmo em diferentes ambientes."
        speaker:
          name: "Dennison Souza"
          photo: "./img/speakers/dennison_souza.jpg"
          url: ""
      -
        name: "Palestra: Virtualização"
        time:
          start: "17:30"
          end: "18:30"
        description: "Virtualização é importante para qualquer setor de TI. O poder que as máquinas virtuais trazem são muito benéficas as empresas, entre elas facilidades de escalabilidade, configuração, gerenciamento e entre outros. Roberto Brandini nos mostrará como ele usa virtualização no dia a dia de sa empresa, a DP Sistemas."
        speaker:
          name: "Roberto Brandini"
          photo: "./img/speakers/roberto_brandini.jpg"
          url: ""
      -
        name: "Sorteio de Brindes e Encerramento"
        time:
          start: "18:30"
          end: "18:30"
        description: ""
        speaker:
          name: ""
          photo: ""
          url: ""


# List of Sponsors
sponsors:
  -
    name: "Google Developers"
    logo: "./img/partners/gd.jpg"
    url: "http://developers.google.com/"


# List of Partners
partners:
  -
    name: "CajuValley"
    logo: "./img/partners/cajuvalley.png"
    url: "https://www.facebook.com/cajuvalley"
  -
    name: "DP Sistemas"
    logo: "./img/partners/dpsistemas.png"
    url: "http://www2.dpsistemas.com.br/"
  -
    name: "Fanese"
    logo: "./img/partners/fanese.png"
    url: "http://portal.fanese.edu.br/"


# About section
about_section:
   title: "Sobre"
   description: ""

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: "Se você tem interesse em contribuir com a comunidade nessa jornada, faça uma proposta :) Nós estamos interessados em testes, Firebase, aplicativos híbridos, criação de APIs, backend, além de conteúdo sobre desenvolvimento Android."
   c4p_url: "http://goo.gl/forms/Wbcc4OQfgB"
   c4p_caption: "Preencha o form!"
   c4p_rules_url: ""
   c4p_rules_caption: ""

# Contact section
contact_section:
   title: "Contato"
   text: "Fale conosco se tiver qualquer dúvida!"
   contacts:
   -
     title: "Email"
     link: "mailto:gdgaracaju@gmail.com"
   -
     title: "Google+"
     link: "https://plus.google.com/communities/100418157558568471841"
   email: "gdgaracaju@gmail.com"
   twitter_url: "http://twitter.com/gdgaracaju"
   twitter_username: "@gdgaracaju"
   show_form: false
   form:
    action: "contato.php"
    name: "What's your name?"
    email: "What's your email?"
    message: "Write a message"
    send_button: "Send"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: false
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"

# Schedule section
schedule_section:
   title: "Programação"
   text: "A programação pode sofrer alterações sem avisos prévios."
   time: "Hora"
   slot: "Atividade"
   description: "Descrição"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: false
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"
