# Jekyll
markdown: rdiscount
highlighter: "rouge"
permalink: /:title.html

# Conference info
conf:
  name: "GCP Next Extended"
  description: "Google Cloud Platform NEXT Extended"
  date: "30 de abril de 2016"
  price: "Gratuito!"
  address: "Travessa Sargento Duque, 85 - Bairro Industrial"
  venue: "FANESE - Faculdade de Administração e Negócios de Sergipe"
  city: "Aracaju, Sergipe"

# Site info
site:
  author: "GDG Aracaju"
  url: "http://android.gdgaracaju.com.br"
  favicon: "http://www.gdgaracaju.com.br/favicon.ico"
  googleanalytics: "UA-49492619-1"
  images:
    cover: "./img/og_image.png"
    facebook: "http://android.gdgaracaju.com.br/img/og_image.png"

subscribe_text: "Inscreva-se no Meetup!"
subscribe_url: "http://www.meetup.com/pt-BR/GDG-Aracaju/events/228405725/"

# Active sections on the website
sections:
  about: true
  c4p: false
  location: true
  speakers: true
  schedule: false
  sponsors: true
  partners: true
  contact: false
  tickets: false

# Organizers list
organizers:
  -
    name: "GDG Aracaju"
    photo: "./img/partners/gdgaracaju.png"
    url: "http://site.gdgaracaju.com.br/"
    bio: ""
    company: ""
  -
    name: "Erick Mendonça"
    photo: "./img/speakers/erick_mendonca.jpg"
    url: "http://github.com/erickmendonca"
    bio: "Formando na Universidade Federal de Sergipe e possui experiência como desenvolvedor e analista de sistemas. Co-organizador do Google Developer Group Aracaju, busca compartilhar conhecimento e aperfeiçoar a comunidade local de desenvolvedores e empreendedores através de eventos técnicos e encontros descontraídos para incentivar o crescimento e a empatia da comunidade local."
    company: "UFS"
  -
    name: "Fernando Mendonça"
    photo: "./img/speakers/fernando.jpg"
    url: "http://github.com/erickmendonca"
    bio: ""
    company: ""
  -
    name: "Raphael Pantaleão"
    photo: "./img/speakers/raphael.jpg"
    url: "http://github.com/raphaelpanta"
    bio: ""
    company: ""
  -
    name: "Roberto Brandini"
    photo: "./img/speakers/roberto_brandini.jpg"
    url: "https://www.facebook.com/roberto.brandini"
    bio: ""
    company: ""

# Speakers list
speakers:
  -
    name: "Dennison Souza"
    url: ""
    photo: "./img/speakers/dennison_souza.jpg"
    title: "Docker container engine"
    details: "Docker permite vocÊ empacotar uma aplicação com todas as suas dependências em uma unidade de desenvolmento software padronizado. Dennisson Souza mostrará como Containers Docker engloba tudo que é preciso para rodar um software e garantir que o software rodará corretamente mesmo em diferentes ambientes."

# Schedule
schedule:
  -
    day: "0204"
    name: "02/04 Talks #2"
    description: "Segundo dia de palestras, aberto à toda comunidade!"
    url: "http://www.meetup.com/pt-BR/GDG-Aracaju/events/229623381/"
    agenda:
      -
        name: "Segurança no Android"
        time:
          start: "14:00"
          end: "15:00"
        description: ""
        speaker:
          name: "Euler Neto"
          photo: "./img/speakers/euler_neto.jpg"
          url: ""
      -
        name: "Firebase e Android"
        time:
          start: "15:00"
          end: "16:00"
        description: ""
        speaker:
          name: "Ygor César"
          photo: "./img/speakers/ygor.jpg"
          url: ""
      -
        name: "A confirmar :)"
        time:
          start: "16:30"
          end: "17:30"
        description: ""
        speaker:
          name: "Ítalo Marcel"
          photo: "./img/speakers/italo_marcel.jpg"
          url: ""
  -
    day: "1903"
    name: "19/03 a 16/04"
    description: "Android para Iniciantes"
    agenda:
      -
        name: "Curso e grupo de estudos"
        time:
          start: "13:00"
          end: "18:00"
        description: ""
        speaker:
          name: "Facilitador: Italo Marcel"
          url: ""
          photo: "./img/speakers/italo_marcel.jpg"
  -
    day: "1203"
    name: "12/03 Talks #1"
    description: "Abertura do Android Jam: palestras, inscrição para grupo de estudos e confraternização!"
    agenda:
      -
        name: "Abertura"
        time:
          start: "14:00"
          end: "14:30"
        description: "Abertura do evento, credenciamento e apresentação do Android Study Jams 2016"
        speaker:
          name: "GDG Aracaju"
          url: "http://site.gdgaracaju.com.br/"
          photo: "./img/gdg.png"
      -
        name: "Internet das Coisas e os Smartphones"
        time:
          start: "14:30"
          end: "15:30"
        description: "Nesta palestra serão apresentados os conceitos de Internet das Coisas, algumas aplicações que podem se beneficiar com a Internet das Coisas e onde os smartphones podem se encaixar nessa aplicações."
        speaker:
          name: "Fernando Mendonça"
          url: "https://github.com/fernandomalmeida"
          photo: "./img/speakers/fernando.jpg"
      -
        name: "Coffee-break"
        time:
          start: "15:30"
          end: "16:00"
        description: "Pausa para o lanche, café e bate-papo"
        speaker:
          name: "GDG Aracaju"
          url: "http://site.gdgaracaju.com.br/"
          photo: "./img/gdg.png"
      -
        name: "Folkes: Minerando dados no Instagram"
        time:
          start: "16:00"
          end: "17:00"
        description: "Muita gente, mas muita gente mesmo tem conta em alguma rede social e o Instagram é uma das favoritas. Mas será que as pessoas sabem do que os dados que elas fornecem para a rede social de fotos é capaz de fazer? Nesse talk vou mostrar um pouco sobre como é legal manipular esses dados e quais informações eles podem nos retornar, por exemplo: o melhor horário de postar uma foto, o melhor dia da semana, quem mais curte suas fotos, se a suas fotos com filtros tem mais likes do que as sem filtros e por ai vamos :)"
        speaker:
          name: "Breno Moura"
          url: "https://github.com/basmoura"
          photo: "./img/speakers/breno_moura.jpg"
      -
        name: "Como a Popcode constrói seus apps - Erros e Acertos"
        time:
          start: "17:00"
          end: "18:00"
        description: "Veja como foi a nossa experiência construindo aplicativos: como trabalhamos, como atender 1 milhão de usuários e dicas do que fazer (e não fazer) na sua startup."
        speaker:
          name: "Hugo Dória"
          photo: "./img/speakers/hugo_doria.jpg"
          url: "https://github.com/hdoria"

# List of Sponsors
sponsors:
  -
    name: "Google Developers"
    logo: "./img/partners/gd.jpg"
    url: "http://developers.google.com/"


# List of Partners
partners:
  -
    name: "CajuValley"
    logo: "./img/partners/cajuvalley.png"
    url: "https://www.facebook.com/cajuvalley"
  -
    name: "DP Sistemas"
    logo: "./img/partners/dpsistemas.png"
    url: "http://www2.dpsistemas.com.br/"
  -
    name: "Fanese"
    logo: "./img/partners/fanese.png"
    url: "http://portal.fanese.edu.br/"


# About section
about_section:
   title: "Sobre"
   description: ""

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: "Se você tem interesse em contribuir com a comunidade nessa jornada, faça uma proposta :) Nós estamos interessados em testes, Firebase, aplicativos híbridos, criação de APIs, backend, além de conteúdo sobre desenvolvimento Android."
   c4p_url: "http://goo.gl/forms/Wbcc4OQfgB"
   c4p_caption: "Preencha o form!"
   c4p_rules_url: ""
   c4p_rules_caption: ""

# Contact section
contact_section:
   title: "Contato"
   text: "Fale conosco se tiver qualquer dúvida!"
   contacts:
   -
     title: "Email"
     link: "mailto:gdgaracaju@gmail.com"
   -
     title: "Google+"
     link: "https://plus.google.com/communities/100418157558568471841"
   email: "gdgaracaju@gmail.com"
   twitter_url: "http://twitter.com/gdgaracaju"
   twitter_username: "@gdgaracaju"
   show_form: false
   form:
    action: "contato.php"
    name: "What's your name?"
    email: "What's your email?"
    message: "Write a message"
    send_button: "Send"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: false
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"

# Schedule section
schedule_section:
   title: "Programação"
   text: "A programação pode sofrer alterações sem avisos prévios."
   time: "Hora"
   slot: "Atividade"
   description: "Descrição"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: false
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"
