# Jekyll
markdown: rdiscount
highlighter: "rouge"
permalink: /:title.html

# Conference info
conf:
  name: "GCP Next Extended '17'"
  description: "Google Cloud Platform NEXT Extended 2017"
  date: "29 de abril de 2017"
  price: "Gratuito!"
  address: "Av. Murilo Dantas, 300 - Farolândia, Aracaju - SE, 49032-490"
  venue: "UNIT Farolândia"
  city: "Aracaju, Sergipe"

# Site info
site:
  author: "GDG Aracaju"
  url: "http://gcp.gdgaracaju.com.br"
  favicon: "http://www.gdgaracaju.com.br/favicon.ico"
  googleanalytics: "UA-49492619-1"
  images:
    cover: "./img/og_image.png"
    facebook: "http://gcp.gdgaracaju.com.br/img/og_image.png"

subscribe_text: "Inscreva-se"
subscribe_url: "https://www.sympla.com.br/google-cloud-next-extended-aracaju__131765"

# Active sections on the website
sections:
  about: true
  c4p: false
  location: true
  speakers: false
  schedule: true
  sponsors: false
  partners: true
  contact: false
  tickets: false

# Organizers list
organizers:
  -
    name: "GDG Aracaju"
    photo: "./img/partners/gdgaracaju.png"
    url: "http://site.gdgaracaju.com.br/"
    bio: ""
    company: ""
  -
    name: "Jéssica Costa"
    photo: "./img/speakers/jessica_costa.jpg"
    url: "http://github.com/erickmendonca"
    bio: ""
    company: ""
  -
    name: "Raphael Pantaleão"
    photo: "./img/speakers/raphael.jpg"
    url: "http://github.com/raphaelpanta"
    bio: ""
    company: ""
  -
    name: "Roberto Brandini"
    photo: "./img/speakers/roberto_brandini.jpg"
    url: "https://www.facebook.com/roberto.brandini"
    bio: ""
    company: ""
  -
    name: "Ítalo Marcel"
    photo: "./img/speakers/italo_marcel.jpg"
    url: "https://www.facebook.com/italo.marcel"
    bio: ""
    company: ""

# Speakers list
speakers:
  -
    name: ""
    url: ""
    photo: ""
    title: ""
    details: ""

# Schedule
schedule:
  -
    day: "2904"
    name: "29/04 GCP Next Extended '17 Aracaju - Horário provisório"
    description: ""
    url: ""
    agenda:
      -
        name: "Google Cloud Next: O que Temos Agora?"
        time:
          start: "8:30"
          end: "09:30"
        description: "Resumo das novidades anunciadas na Google Cloud Next '17'"
        speaker:
          name: "Jéssica Costa"
          photo: "./img/speakers/jessica_costa.jpg"
          url: ""
      -
        name: "Escalabilidade na Nuvem Através de Microserviços"
        time:
          start: "9:30"
          end: "11:00"
        description: "Visão geral de Microserviços e como arquitetar sua aplicação para a nuvem."
        speaker:
          name: "Raphael Pantaleão e Diego Melo"
          photo: "./img/speakers/raphael_diego.jpg"
          url: ""
      -
        name: "Filosofia Cloud na Gestão de Equipes e Desenvolvimento de Projetos. Case: Laboratório 99"
        time:
          start: "11:00"
          end: "12:00"
        description: "Muito mais que uma palestra técnica, o 99lab irá compartilhar como aplica toda a filosofia Cloud para a gestão de seus projetos e o desenvolvimento dos projetos que a empresa se envolve. À partir de uma metodologia desenvolvida pelo 99lab, a empresa une pessoas com diferentes habilidades de todo o Brasil pra fazer jogos acontecerem."
        speaker:
          name: "Daniel Caldas"
          photo: "./img/speakers/daniel_caldas.jpg"
          url: ""
      -
        name: "Almoço"
        time:
          start: "12:00"
          end: "13:00"
        description: ""
        speaker:
          name: ""
          photo: ""
          url: ""
      -
        name: "Google for Students (a definir)"
        time:
          start: "13:00"
          end: "13:50"
        description: ""
        speaker:
          name: ""
          photo: ""
          url: ""
      -
        name: "Tá Pegando Fogo Bicho: Como modelar seu projeto com Firebase"
        time:
          start: "13:50"
          end: "14:40"
        description: "O Firebase veio pra ficar e é incrível no que se propõe fazer. Porém existem alguns detalhes que as pessoas não te contaram que pode ser decisivos ao construir seu projeto. É justamente isso que vamos conversar: contras e prós, funcionalidades desconhecidas, tratamento de transações, técnicas de arquitetura de dados."
        speaker:
          name: "Eduardo Borges"
          photo: "./img/speakers/eduardo_borges.jpg"
      -
        name: "Novos desafios para as aplicações na utilização de Cloud Computing e IoT (Internet of Things)"
        time:
          start: "14:40"
          end: "15:30"
        description: "A palestra visa esclarecer quais são os principais desafios encontrados hoje para que as aplicações possam oferecer os serviços ofertados utilizando a Cloud Computing e Internet of Things. A IoT se integra a Cloud e Big Data aumentando as estratégias de mobilidade e com isso surgindo questões como segurança e o volume dos dados gerados."
        speaker:
          name: "Mayka de Souza Lima"
          photo: "./img/speakers/mayka.jpg"
          url: ""
      -
        name: "Coffee Break"
        time:
          start: "15:30"
          end: "15:45"
        description: ""
        speaker:
          name: ""
          photo: ""
          url: ""
      -
        name: "Alline Oliveira"
        time:
          start: "15:45"
          end: "16:45"
        description: "Papo aberto com Alline Oliveira, sobre Google Cloud, Google Developer Experts e Outros."
        speaker:
          name: "Alline Oliveira"
          photo: "./img/speakers/alline.jpg"
          url: ""
      -
        name: "Encerramento"
        time:
          start: "16:45"
          end: "17:00"
        description: ""
        speaker:
          name: ""
          photo: ""
          url: ""

# List of Sponsors
sponsors:
  -
    name: "Google Developers"
    logo: "./img/partners/gd.jpg"
    url: "http://developers.google.com/"


# List of Partners
partners:
  -
    name: "UNIT"
    logo: "./img/partners/unit.jpg"
    url: "https://www.unit.br"

# About section
about_section:
   title: "Sobre"
   description: ""

# Call for papers section
c4p_section:
   title: "Call for papers"
   text: "Se você tem interesse em contribuir com a comunidade nessa jornada, faça uma proposta :) Nós estamos interessados em testes, Firebase, aplicativos híbridos, criação de APIs, backend, além de conteúdo sobre desenvolvimento Android."
   c4p_url: "http://goo.gl/forms/Wbcc4OQfgB"
   c4p_caption: "Preencha o form!"
   c4p_rules_url: ""
   c4p_rules_caption: ""

# Contact section
contact_section:
   title: "Contato"
   text: "Fale conosco se tiver qualquer dúvida!"
   contacts:
   -
     title: "Email"
     link: "mailto:gdgaracaju@gmail.com"
   -
     title: "Google+"
     link: "https://plus.google.com/communities/100418157558568471841"
   email: "gdgaracaju@gmail.com"
   twitter_url: "http://twitter.com/gdgaracaju"
   twitter_username: "@gdgaracaju"
   show_form: false
   form:
    action: "contato.php"
    name: "What's your name?"
    email: "What's your email?"
    message: "Write a message"
    send_button: "Send"

# Location section
location_section:
   title: "Local"

# Partners section
partners_section:
   title: "Parceiros"
   show_your_logo_here: false
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"

# Schedule section
schedule_section:
   title: "Programação"
   text: "A programação pode sofrer alterações sem avisos prévios."
   time: "Hora"
   slot: "Atividade"
   description: "Descrição"

# Speakers section
speakers_section:
   title: "Palestrantes"

# Sponsors section
sponsors_section:
   title: "Patrocinadores"
   show_your_logo_here: false
   your_logo_here_link: "mailto:gdgaracaju@gmail.com"
